name: test-schedule

# Trigger the workflow on pull request
on:
#  pull_request
#  schedule:
#    - cron: '*/10 * * * *'
  workflow_dispatch:


jobs:
#  approve-prs:
#    runs-on: ubuntu-latest
#    name: Merge valid PRs 
#    steps:
#      - name: Approve valid workflows
#        uses: Cian911/gomerge-action@master
#        with:
#          repository: ${{ github.repository }}
#          github_token: ${{ secrets.TEST }}
#          labels: ""

  schedule_merge_prs:
    name: Scheduled PR Merge Job
    runs-on: ubuntu-latest
    outputs:
      mergedPRs: ${{ steps.merge-prs.outputs.MPR_LIST }}
      mergeFailPR: ${{ steps.merge-prs.outputs.MC_PR_NO }}
    steps:
      - id: merge-prs
        uses: gr2m/merge-schedule-action@v2
        with:
          # Merge method to use. Possible values are merge, squash or
          # rebase. Default is merge.
          merge_method: rebase
          #  Time zone to use. Default is UTC.
          #time_zone: "Asia/Tokyo"
        env:
          GITHUB_TOKEN: "${{ secrets.TEST }}"

  display_pr_status_job:
    name: Show status of PR
    runs-on: ubuntu-latest
    needs: schedule_merge_prs
    steps:
      - run: echo ${{needs.schedule_merge_prs.outputs.mergedPRs}} ${{needs.schedule_merge_prs.outputs.mergeFailPR}}



