name: Test-Validate
on:
  push:
    branches: [ "nonprod/RITM*", "prod/RITM*" ]
  workflow_dispatch:
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Current Branch
        uses: actions/checkout@v3
        
      - name: Run a one-line script
        run: echo Validate Success!

  create-implement-branch:
    needs: validate
    runs-on: ubuntu-latest
    outputs:
        branch: ${{ steps.check-environment.outputs.branch }}
        environment: ${{ steps.check-environment.outputs.en}}
#        branch-nonprod: ${{ steps.get-environment-nonprod.outputs.branch }}
#        branch-prod: ${{ steps.get-environment-prod.outputs.branch }}
    steps:
      - name: Checkout Current Branch
        uses: actions/checkout@v3

      - name: Check Branch Environment
        shell: bash
        run: |
          if [[ "${{ github.ref }} =~ ^"refs/heads/nonprod/" ]]; then
            echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/nonprod/}}" >> $GITHUB_OUTPUT
            echo "en=Non-Production"
          elif [[ "${{ github.ref }} =~ ^"refs/heads/prod/" ]]; then
            echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/prod/}}" >> $GITHUB_OUTPUT
            echo "en=Production"
          fi
        id: check-environment

      - name: Create Implement Branch
        env: 
            GITHUB_REPOSITORY: ${{ github.repository }}
            GITHUB_TOKEN: ${{ secrets.TEST }}
            base_branch: "0d9657a7a4b5a420b574f0ec90caf3a01646880f" #rev-parse not working --'main' branch 
            new_branch: 'implement/${{ steps.check-environment.outputs.branch }}'
        run: |
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" -d "{\"ref\":\"refs/heads/$new_branch\",\"sha\":\"$(git rev-parse $base_branch)\"}" "https://api.github.com/repos/$GITHUB_REPOSITORY/git/refs"
          
  create-pull-request:
    needs: create-implement-branch
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Current Branch
      uses: actions/checkout@v3

    - name: Get Current Date
      run: echo CURRENTDATE=$(date '+%Y-%m-%d') >> $GITHUB_ENV

    - name: Create Pull Request [ Non-Production ]
      uses: diillson/auto-pull-request@v1.0.1
      with:
        source_branch: ""
        destination_branch: "implement/${{ needs.create-implement-branch.outputs.branch }}"
        pr_title: "[ ${{ needs.create-implement-branch.outputs.en }} ] Deploy ${{ needs.create-implement-branch.outputs.branch }}"
        pr_body: |
          :crown: *Automated Pull Request from Network Guardian*
            Request Ticket : ${{ needs.create-implement-branch.outputs.branch }}
            Environment: ${{ needs.create-implement-branch.outputs.en }}
      
          /schedule ${{ env.CURRENTDATE }}
        pr_draft: false                    
        pr_label: "nsg-deployment"         
        github_token: "${{ secrets.TEST }}"
