name: test-schedule

# Trigger the workflow on pull request
on:
#  pull_request
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:


jobs:
  scheduled_merge:
    name: Merge Scheduler
    runs-on: ubuntu-latest
    steps:
      - name: Merging Pending NSG Pull Requests
        uses: gr2m/merge-schedule-action@v2
        with:
          time_zone: 'Asia/Hong_Kong'
          merge_method: merge
          automerge_fail_label: 'failed-scheduled-merged'
        env:
          GITHUB_TOKEN: "${{ secrets.TEST }}"

#  scheduled_merge:
#    name: Merge Scheduler
#    runs-on: ubuntu-latest
#    steps:
#      - name: Merging Pending NSG Pull Requests 
#        uses: Cian911/gomerge-action@master
#        with:
#          repository: ${{ github.repository }}
#          github_token: ${{ secrets.TEST }}
#          labels: nsg-deployment,Non-Production
#          approve: true