name: Test Validate
on:
  push:
    branches: [ "nonprod/RITM*", "prod/RITM*" ]
  workflow_dispatch:
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Current Branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TEST }}
        
      - name: Run a one-line script
        run: echo Validate Success! >> test.txt

      - name: Get Branch Details
        run: |
          if [[ "${{ github.ref }}" =~ ^"refs/heads/nonprod/" ]]; then
              request=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/nonprod/}}"
              echo "new_branch=nonprod-validated/$request" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" =~ ^"refs/heads/prod/" ]]; then
              request=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/prod/}}"
              echo "new_branch=prod-validated/$request" >> $GITHUB_ENV
          fi

      - name: Push to Validated Branch
        uses: EndBug/add-and-commit@v9
        with:
          new_branch: ${{ env.new_branch }}
          message: 'test'
          add: 'test.txt'

