name: Test-Validate
on:
  push:
    branches: [ "nonprod/RITM*" ]
  workflow_dispatch:
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
        
      - name: Run a one-line script
        run: echo Validate Success!

  create-implement-branch:
    needs: validate
    runs-on: ubuntu-latest
    outputs:
        branch-name: ${{ steps.get-validate-branch.outputs.branch }}
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
      - name: Get Validate Branch
        shell: bash
        run:  echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/nonprod/}}" >> $GITHUB_OUTPUT
        id: get-validate-branch
#      - name: Checkout Main Branch
#        uses: actions/checkout@v3
#        with:
#          ref: implement/nonprod
#          token: "${{ secrets.TEST }}"
#      - name: Create New Implement Branch
#        uses: peterjgrainger/action-create-branch@v2.2.0
#        env:
#          GITHUB_TOKEN: "${{ secrets.TEST }}"
#        with:
#          branch: 'refs/heads/implement/${{ steps.get-validate-branch.outputs.branch }}'
      - name: Create Implement Branch
        env: 
            GITHUB_TOKEN: ${{ secrets.TEST }}
            base_branch: 'implement/nonprod'
            new_branch: 'implement/${{ steps.get-validate-branch.outputs.branch }}'
        run: |
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" -d "{\"ref\":\"refs/heads/$new_branch\",\"sha\":\"$(git rev-parse $base_branch)\"}" "https://api.github.com/repos/$GITHUB_REPOSITORY/git/refs"
          
  create-pull-request:
    needs: create-implement-branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: get-date
      run: echo CURRENTDATE=$(date '+%Y-%m-%d') >> $GITHUB_ENV
    - name: pull-request
      uses: diillson/auto-pull-request@v1.0.1
      with:
          source_branch: ""                                 # If blank, default: triggered branch
          destination_branch: "implement/${{ needs.create-implement-branch.outputs.branch-name }}"                      # If blank, default: master
          pr_title: "Deploy ${{ needs.create-implement-branch.outputs.branch-name }}" # Title of pull request
          pr_body: |                                        # Full markdown support, requires pr_title to be set
            :crown: *An automated PR*
      
            Created by [diillson/auto-pull-request](https://github.com/diillson/auto-pull-request)
            /schedule ${{ env.CURRENTDATE }}
          pr_draft: false                                    # Creates pull request as draft
          pr_label: "nsg-deployment"                               # Comma-separated list (no spaces)
          github_token: "${{ secrets.TEST }}"      # If blank, default: secrets.GITHUB_TOKEN

