name: test-schedule

# Trigger the workflow on pull request
on:
#  pull_request
  workflow_dispatch:


jobs:
  autoapprove:
    name: Auto Approve a PR by dependabot
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Auto approve
        uses: hmarr/auto-approve-action@v3.0.0
        with:
          github-token: ${{ secrets.TEST }}
  automerge:
    name: Auto merge after successful checks
    needs: autoapprove
    runs-on: ubuntu-latest
    steps:
      - name: Auto merge
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.TEST }}
          MERGE_LABELS: automerge
          MERGE_METHOD: merge
          MERGE_DELETE_BRANCH: true


