name: Test-Implement
on:
  push:
    branches: [ "test" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
        
      - name: Run a one-line script
        run: echo Hello, Implement!