name: Test Delete Implement Branches
on:
#  schedule:
#    - cron: '* 18 * * *' # Non-Production
#    - cron: '* 21 * * 5' # Production
    workflow_dispatch:

jobs:
  implement:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TEST }}

      - name: Delete Done Branches
        run: |
          echo "Branches that will be remove:"
          git branch -a | grep "done"
