name: Test Implement
on:
  pull_request:
    types: [closed]
    branches: [ "implement/RITM*" ]

  workflow_dispatch:
jobs:
  implement:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TEST }}
        
      - name: Run a one-line script
        run: echo Hello, Implement!
      
      - name: Get Branch Details
        run: |
          echo ${{ github.ref }}
          if [[ "${{ github.ref }}" =~ ^"refs/heads/nonprod-validated/" ]]; then
            request=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/nonprod/}}
            echo "branch_env=Non-Production" >>$GITHUB_ENV"
            echo "new_branch=implement/${request}" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" =~ ^"refs/heads/prod-validated/" ]]; then
            request=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/prod/}}
            echo "branch_env=Production" >>$GITHUB_ENV"
            echo "new_branch=implement/${request}" >> $GITHUB_ENV
          fi
      
#      - name: Update Branch Name
#        run: |
#          git branch -m "${{ env.new_branch }}-${{ env.branch_env }}" "${{ env.new_branch }}"-"${{ env.branch_env }}-done"
#          git push origin :${{ env.new_branch }}-${{ env.branch_env }} ${{ env.new_branch }}"-"${{ env.branch_env }}-done
#          git push origin -u "${{ env.new_branch }}"-"${{ env.branch_env }}-done"
          