name: Test-Pull-Request
on:
    push:
      branches:
      - "test-*"  # Support wildcard matching
  
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: pull-request
      uses: diillson/auto-pull-request@v1.0.1
      with:
          source_branch: ""                                 # If blank, default: triggered branch
          destination_branch: "test"                      # If blank, default: master
          pr_title: "Pulling ${{ github.ref }} into master" # Title of pull request
          pr_body: |                                        # Full markdown support, requires pr_title to be set
            :crown: *An automated PR*
      
            Created by [diillson/auto-pull-request](https://github.com/diillson/auto-pull-request)_
          pr_draft: true                                    # Creates pull request as draft

          github_token: ${{ secrets.TEST }}      # If blank, default: secrets.GITHUB_TOKEN
            #          pr_template: ".github/PULL_REQUEST_TEMPLATE.md"   # Path to pull request template, requires pr_title to be set, excludes pr_body
#          pr_reviewer: "diillson,worker"                         # Comma-separated list (no spaces)
#          pr_assignee: "diillson,worker"                         # Comma-separated list (no spaces)
#          pr_label: "auto-pr"                               # Comma-separated list (no spaces)
#          pr_milestone: "Milestone 1"                       # Milestone name no Required it is comment
#          pr_allow_empty: true                              # Creates pull request even if there are no changes
