name: Test Implement
on:
  pull_request:
    types: [closed]
    branches: [ "implement/RITM*" ]

  workflow_dispatch:
jobs:
  implement:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TEST }}
        
      - name: Run a one-line script
        run: echo Hello, Implement!
      
      - name: Update Branch Name
        run: |
          if [[ "${{ github.ref }}" =~ "-Non-Production" ]]; then
            request=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/nonprod-validated/}}
            new_request=($(echo $request | sed 's/nonprod-validated\///g))
            old_branch="implement/${new_request}-Non-Production"
            new_branch="${old_branch}-done"
          elif [[ "${{ github.ref }}" =~ "-Production" ]]; then
            request=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/prod-validated/}}
            new_request=($(echo $request | sed 's/prod-validated\///g))
            old_branch="implement/${new_request}-Production" >> $GITHUB_ENV
          fi
          new_branch="${old_branch}-done"
          echo $request
          echo $old_branch
          echo $new_branch

#      - name: Update Branch Name
#        run: |
#          git branch -m "${{ env.new_branch }}-${{ env.branch_env }}" "${{ env.new_branch }}"-"${{ env.branch_env }}-done"
#          git push origin :${{ env.new_branch }}-${{ env.branch_env }} ${{ env.new_branch }}"-"${{ env.branch_env }}-done
#          git push origin -u "${{ env.new_branch }}"-"${{ env.branch_env }}-done"
          