name: Test Implement
on:
  pull_request:
    types: [closed]
    branches: [ "implement/RITM*" ]

  workflow_dispatch:
jobs:
  implement:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TEST }}
        
      - name: Run a one-line script
        run: echo Hello, Implement!
      
      - name: Update Implement Branch
        run: |
              request_environment=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
              echo $request_environment
#              git branch -m implement/${request_environment}-done
#              git push origin :implement/${request_environment} implement/${request_environment}-done
#              git push origin -u implement/${request_environment}-done