name: Test-Validate
on:
  push:
    branches: [ "test-*" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
        
      - name: Run a one-line script
        run: echo Hello, world!

  create-pull-request:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: pull-request
      uses: diillson/auto-pull-request@v1.0.1
      with:
          source_branch: ""                                 # If blank, default: triggered branch
          destination_branch: "test"                      # If blank, default: master
          pr_title: "Pulling ${{ github.ref }} into master" # Title of pull request
          pr_body: |                                        # Full markdown support, requires pr_title to be set
            :crown: *An automated PR*
      
            Created by [diillson/auto-pull-request](https://github.com/diillson/auto-pull-request)_
          pr_draft: true                                    # Creates pull request as draft
          github_token: ${{ secrets.TEST }}      # If blank, default: secrets.GITHUB_TOKEN

