name: Test Merge Scheduler
on:
#  schedule:
#    - cron: '* 18 * * *' # Non-Production
#    - cron: '* 21 * * 5' # Production
  workflow_dispatch:


jobs:
  scheduled_merge:
    name: Merge Scheduler
    runs-on: ubuntu-latest
    steps:
      - name: Merging Pending NSG Pull Requests
        uses: gr2m/merge-schedule-action@v2
        with:
          time_zone: 'Asia/Hong_Kong'
          merge_method: merge
          automerge_fail_label: 'failed-scheduled-merged'
        env:
          GITHUB_TOKEN: "${{ secrets.TEST }}"
